### ISSUE TITLE
Why does the test Block Stacking Demo fail to run after installation?

### ISSUE THREAD

**Issue by lijle** [ColinKohler/BulletArm#4]
Whether I ran it directly in Pycharm or typed: python tutorials/block_stacking_demo.py on the terminal, the result would look like this
![bulletarm1](https://user-images.githubusercontent.com/63141243/187853887-c43d1bd4-cfeb-4eee-972f-bf260b3ff7cb.png)
![bulletarm2](https://user-images.githubusercontent.com/63141243/187853896-215d9cea-1885-4bfa-9e40-14091f56b724.png)

**Comment by lijle** [comment]
Does this project not support Windows?
https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857/33

**Comment by ColinKohler** [comment]
At the moment, we do not support Windows as we have no one who develops on Windows who could test. In terms of your issue, you should be able to change the 1 in line 5 to 0 like so: `env = env_factory.createEnvs(0, 'block_stacking', env_config) `. This will run everything in the main thread and not use any multiprocessing. If you need to run multiple simulators in parallel it looks like you would have to look into using [Pathos](https://github.com/uqfoundation/pathos) and dill instead of the generic multiprocessing library. Unfortunately, we need to be able to pickle lambdas (which windows can't do) in order to package the configurations for each simulator in the mutli-simulator setting.

**Comment by lijle** [comment]
Thank you for answering my question, I will consider using Linux to run later


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ColinKohler/BulletArm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ColinKohler/BulletArm] Why does the test Block Stacking Demo fail to run after installation? (Issue #4)





 
At the moment, we do not support Windows as we have no one who develops on Windows who could test. In terms of your issue, you should be able to change the 1 in line 5 to 0 like so: env = env_factory.createEnvs(0, 'block_stacking', env_config) . This will run everything in the main thread and not use any multiprocessing. If you need to run multiple simulators in parallel it looks like you would have to look into using Pathos and dill instead of the generic multiprocessing library. Unfortunately, we need to be able to pickle lambdas (which windows can't do) in order to package the configurations for each simulator in the mutli-simulator setting.
